version: '3.8'

volumes:
  tmp-data:
  mysql-data:
  redis-data:

services:
  app: &app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PHP_VERSION: 8.1
    user: '${APP_UID:-10001}:${APP_GID:-10001}'
    environment:
      PS1: '\[\033[1;32m\]\[\033[1;36m\][\u@\h] \[\033[1;34m\]\w\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]'
      HOME: /tmp
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - tmp-data:/tmp:rw
      - .:/app:rw
      - ./docker/php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini:ro
      - ./docker/php/custom-fpm.conf:/usr/local/etc/php-fpm.d/custom-fpm.conf:ro
    depends_on:
      mysql: { condition: service_healthy }
      redis: { condition: service_healthy }

  web:
    <<: *app
    command: php-fpm
    ports:
      - '9000:9000/tcp'
    healthcheck:
      test: php-fpm-healthcheck
      interval: 2s
      timeout: 2s

  queue:
    <<: *app
    command: php /app/artisan queue:work --memory=256 --sleep=1

  cron:
    <<: *app
    command: supercronic /etc/supercronic/laravel # it runs artisan schedule:run

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql:rw
    ports:
      - '3306:3306/tcp'
    healthcheck:
      test: mysqladmin ping -h mysql -u root -ppassword
      interval: 2s
      timeout: 5s
      start_period: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data:rw
    ports:
      - '6379/tcp'
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 500ms
      timeout: 1s

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      args:
        NODE_VERSION: 16
    user: '${APP_UID:-10001}:${APP_GID:-10001}'
    ports:
      - '5173:5173/tcp'
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/app:rw
    command: npm run dev

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        NGINX_VERSION: stable
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
    volumes:
      - .:/app:ro
    depends_on:
      web: { condition: service_healthy }
